trigger:
- master

resources:
  repositories:
  - repository: self

stages:
- stage: dev
  jobs:
  - deployment:
    environment: development
    variables:
      - group: nock-fetch
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - script: echo "//$(registry)/:_authToken=$(access_token)" > .npmrc
            - task: NodeTool@0
              inputs:
                versionSpec: '10.x'
              displayName: 'Install Node.js'
            - task: Npm@1
              inputs:
                command: install
                customRegistry: useNpmrc
            - task: Npm@1
              inputs:
                command: custom
                customRegistry: useNpmrc
                customCommand: run ci
            - task: PublishTestResults@2
              condition: succeededOrFailed()
              inputs:
                testRunner: JUnit
                testResultsFiles: '**/junit.xml'
            - task: PublishBuildArtifacts@1
              inputs:
                artifactName: test-report 
            # - task: Npm@1
            #   command: publish
            #   customRegistry: useNpmrc
            #   publishPackageMetadata: true
            - script: rm .npmrc
              condition: succeededOrFailed()
