trigger:
- master

resources:
  repositories:
  - repository: self

stages:
- stage: dev
  jobs:
  - deployment:
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
        steps:
        - checkout: self
        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'
        - script: |
            npm install
            npm run test
          displayName: 'npm install and test'
